version: '3.8'

services:
  mysql-m:
    image: mysql:8.0
    container_name: mysql-m
    environment:
      - "MYSQL_DATABASE=hsa"
      - "MYSQL_USER=hsa"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=root"
    volumes:
      - ./master_data:/var/lib/mysql
      - ./docker/mysql/master/master.cnf:/etc/mysql/conf.d/master.cnf
      - ./docker/mysql/master/init-master.sql:/docker-entrypoint-initdb.d/init-master.sql
    ports:
      - "3305:3306"
    networks:
      - hsa_mysql_cluster_net
  
  mysql-s1:
    image: mysql:8.0
    container_name: mysql-s1
    environment:
      - "MYSQL_DATABASE=hsa"
      - "MYSQL_USER=hsa"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=root"
    volumes:
      - ./slave1_data:/var/lib/mysql
      - ./docker/mysql/slave/slave_1.cnf:/etc/mysql/conf.d/slave_1.cnf
    ports:
      - "3307:3306"
    networks:
      - hsa_mysql_cluster_net
    depends_on:
      - mysql-m
  
  mysql-s2:
    image: mysql:8.0
    container_name: mysql-s2
    environment:
      - "MYSQL_DATABASE=hsa"
      - "MYSQL_USER=hsa"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=root"
    volumes:
      - ./slave2_data:/var/lib/mysql
      - ./docker/mysql/slave/slave_2.cnf:/etc/mysql/conf.d/slave_2.cnf
    ports:
      - "3308:3306"
    networks:
      - hsa_mysql_cluster_net
    depends_on:
      - mysql-m
      
  hsa_mysql_cluster_server:
    container_name: hsa_mysql_cluster_server
    build:          ./server
    expose:
      - 3000
    ports:
      - 0.0.0.0:9999:3000
      - 0.0.0.0:9998:9249
    command:        npm run start:debug
    volumes:
      - ./server:/usr/src/app
    networks:
      - hsa_mysql_cluster_net

networks:
  hsa_mysql_cluster_net:
    driver: bridge
